[[plugins]]
repo = 'Shougo/dein.vim'

# When `LuaSnip` is loaded lazily, the internal autocmd process deletes all
# the syntax of that buffer. Therefore, this plugin is intended to be loaded
# without delay.
# Problem: _luasnip_lazy_load function called on "FileType" event
# (L3MON4D3\LuaSnip\plugin\luasnip.lua:86)
[[plugins]]
repo = 'L3MON4D3/LuaSnip'
if = 'has("nvim-0.7")'
lua_post_source = '''
  local luasnip = require('luasnip')
  luasnip.config.set_config({
    history = true,
    updateevents = 'TextChanged,TextChangedI',
  })

  vim.api.nvim_create_autocmd('InsertLeave', {
    group = vim.api.nvim_create_augroup('user_luasnip', {}),
    callback = function()
      local bufnr = vim.api.nvim_get_current_buf()
      if
        luasnip.session.current_nodes[bufnr]
        and not luasnip.session.jump_active
      then
        luasnip.unlink_current()
      end
    end,
  })
'''
