[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
if = 'has("nvim-0.5")'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
if = 'has("nvim-0.7.0")'

[[plugins]]
repo = 'rcarriga/nvim-notify'
if = 'has("nvim-0.5")'
lua_post_source = 'require("notify").setup()'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
if = 'has("nvim-0.8.0")'
lua_post_source = 'require("gitsigns").setup()'

# Completion and code analysis
#=============================================================================
[[plugins]]
repo = 'L3MON4D3/LuaSnip'
if = 'has("nvim-0.7")'
lua_post_source = 'require("plugins/luasnip").setup()'

# Syntax
#=============================================================================
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim-0.7")'
hook_post_update = ':TSUpdate'
lua_post_source = 'require("plugins/treesitter").setup()'

[[plugins]]
repo = 'nvim-treesitter/playground'
depends = ['nvim-treesitter']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
depends = ['nvim-treesitter']

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
depends = ['nvim-treesitter']
lua_add = 'vim.g.skip_ts_context_commentstring_module = true'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
depends = ['nvim-treesitter']

# Finder
#=============================================================================
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
if = 'has("nvim-0.7")'
depends = ['plenary.nvim', 'nvim-web-devicons']
lua_post_source = 'require("plugins/telescope").setup()'

[[plugins]]
repo = 'nvim-telescope/telescope-ui-select.nvim'
if = 'has("nvim-0.7")'
depends = ['telescope.nvim']
lua_post_source = '''
  -- Load extensions for telescope.nvim
  require('telescope').load_extension('ui-select')
'''

# Filer
#=============================================================================
[[plugins]]
repo = 'obaland/vfiler.vim'
depends = ['vfiler-column-devicons']
lua_post_source = 'require("plugins/vfiler").setup()'

[[plugins]]
repo = 'obaland/vfiler-column-devicons'

# Utility
#=============================================================================
[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
if = 'has("nvim-0.4.0")'
lua_post_source = 'require("colorizer").setup()'
