[ftplugin]
cs = '''
  setlocal tabstop=4
  setlocal shiftwidth=4
  setlocal softtabstop=4
'''

html = '''
  filetype plugin indent on
  setlocal tabstop=2
  setlocal shiftwidth=2
  setlocal softtabstop=2
'''

php = '''
  filetype plugin indent on
  setlocal tabstop=4
  setlocal shiftwidth=4
  setlocal softtabstop=4
'''
