# Syntax
#=============================================================================
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
rev = 'main'
if = 'has("nvim-0.12")'
hook_post_update = ':TSUpdate'
lua_source = 'require("plugins/treesitter").setup()'
