# Syntax
#=============================================================================
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim-0.11")'
hook_post_update = ':TSUpdate'
lua_source = 'require("plugins/treesitter").setup()'
