[selene]
base = "lua51"
name = "vim"

[vim]
any = true

[jit]
any = true

[[describe.args]]
type = "string"
[[describe.args]]
type = "function"

[[it.args]]
type = "string"
[[it.args]]
type = "function"

[[before_each.args]]
type = "function"
[[after_each.args]]
type = "function"

[[assert.is_false.args]]
type = "any"

[assert.is_nil]
any = true

[assert.is_not_nil]
any = true

[[assert.is_equal.args]]
type = "any"
[[assert.is_equal.args]]
type = "any"

[[assert.is_true.args]]
type = "any"

[[assert.equals.args]]
type = "any"

[[assert.equal.args]]
type = "any"
[[assert.equal.args]]
type = "any"

[[assert.not_equal.args]]
type = "any"
[[assert.not_equal.args]]
type = "any"

[[assert.same.args]]
type = "any"

[[assert.truthy.args]]
type = "any"

[[assert.spy.args]]
type = "any"

[[assert.stub.args]]
type = "any"
